### ISSUE TITLE
Hyvä compatibility

### ISSUE THREAD

**Issue by amenk** [iMi-digital/magento2-friendly-captcha#13]
Implement Hyvä compatibility 

PRs welcome :-)
CC @sprankhub

**Comment by sprankhub** [comment]
See #18.

**Comment by DanieliMi** [comment]
@sprankhub thank you very much for this contribution! I just released [1.5.0](https://github.com/iMi-digital/magento2-friendly-captcha/releases/tag/1.5.0).

**Comment by DanieliMi** [comment]
As noted in #18, the MR was not merged. This is fixed in [1.5.1](https://github.com/iMi-digital/magento2-friendly-captcha/releases/tag/1.5.1).
