### ISSUE TITLE
widget.module.js is missing from pub/static

### ISSUE THREAD

**Issue by lmuskalla** [iMi-digital/magento2-friendly-captcha#2]
Hey there!

I tried installing this module, got it to run, but the file widget.module.js is missing from the pub/static folder. Whatever I do, it doesn't get deployed to static content. I've tried setting a requirejs-config file, moving the view/frontend/ folder of the module to app/design, etc. Nothing seems to work.

Do you have any idea what the issue could be?
We are running Magento 2.3.5-p1. I didn't install the module through Composer, but rather downloaded it through Git and installed it manually, like I always install Magento modules (this is necessary because of the way our deployment pipeline is set up).

I would much appreciate any help on this.

**Comment by amenk** [comment]
Hi, we require the module via composer, which might solve the problem, but I am not sure if that is the issue.

You might want to ask at Magento.stackexchange.com ? Feel free to post the link here.

**Comment by lmuskalla** [comment]
I've got it to work without Composer by copying the widget.min.js & widget.module.min.js files from the repository to IMI/FriendlyCaptcha/view/frontend/web/js/friendly-catpcha/ and include them in IMI/FriendlyCaptcha/view/frontend/templates/imi_friendly_captcha_js.phtml with
`<script src="<?= $block->getViewFileUrl('IMI_FriendlyCaptcha::js/friendly-captcha/widget.module.min.js')?>" type="module" async></script>
<script nomodule src="<?= $block->getViewFileUrl('IMI_FriendlyCaptcha::js/friendly-captcha/widget.min.js')?>" async></script>`

This removes the necessity for a requirejs-config file.
In case this helps anyone :)

**Comment by amenk** [comment]
Okay, thanks for the information.
