### ISSUE TITLE
JS Uncaught TypeError: d.createObjectURL is not a function

### ISSUE THREAD

**Issue by xmedia2000** [iMi-digital/magento2-friendly-captcha#26]
We have implemented Friendly Captcha in the Magento2 Footer of our shop.
On some pages (all with threejs) we get the following error:

```
Uncaught TypeError: d.createObjectURL is not a function
    at p.init (widget.module.min.js:1:27202)
    at _.initWorkerGroup (widget.module.min.js:1:34401)
    at _.init (widget.module.min.js:1:32390)
    at new _ (widget.module.min.js:1:32168)
    at f (widget.module.min.js:1:38897)
    at widget.module.min.js:1:39044
```
All other pages are working as expected.
Any ideas?

**Comment by amenk** [comment]
@xmedia2000 can you share the URL of such a page?

**Comment by xmedia2000** [comment]
hi amenk,
here you can find the link:
[](https://www.setrada.de/polsterbank-easy.html)

**Comment by merlinfuchs** [comment]
The global URL variable (`window.URL`) is overwritten by a script in your page:
<img width="625" alt="grafik" src="https://user-images.githubusercontent.com/33966852/231814109-53484d97-0f71-4f7f-a9a4-bd56f4ea3a2a.png">

Either rename that variable or not define it globally. Many javascript libraries will depend on `window.URL` being there, so it's usually a bad idea to overwrite it.

**Comment by amenk** [comment]
Perfect, thanks for the Feedback - closing this :-)
