### ISSUE TITLE
An extra captcha when we do not have newsletter form on the page

### ISSUE THREAD

**Issue by iranimij** [iMi-digital/magento2-friendly-captcha#31]
Our newsletter captcha is enabled, but on some pages we do not have a newsletter form, 
and it shows it at the bottom of the page, I think we can fix this issue easily by first checking if the element exists on the page and if the newsletter form does not exist we can remove it.

Thanks.

**Comment by sprankhub** [comment]
Sorry for the late feedback!

Flickering is a valid concern, although I would argue that it is not that bad or not visible at all:

1. The block is inserted at the bottom of the page (`before.body.end`).
2. The block would only actually show something when the third-party FriendlyCaptcha script is loaded and evaluated. By then, inline scripts should already be evaluated. So I think it would be removed before anything is actually visible.

Having said that, I like your idea, although I think it has its drawbacks as well. What if people insert newsletter blocks under different layout names? We would not be able to support this then.

> We could also check if newsletter is active in the config, but sometimes the block might be removed on certain pages via other means.

That would not be enough for our use case.

**Comment by amenk** [comment]
@sprankhub thanks for the feedback

In our case, we did not use the newsletter at all, so we just deactivated the Captcha for it -> solved

I agree with your reasoning and the solution is much easier than what I was planning, so I guess we will merge this for now.

@DanieliMi what are your thoughts?
We should also add a sentence to the readme and recommend to disable the Newsletter Captcha if the newsletter is not in use.

**Comment by sprankhub** [comment]
@DanieliMi, could you give your feedback here, so that we can proceed?

**Comment by iranimij** [comment]
I tested it and it seemed ok @amenk

**Comment by amenk** [comment]
Thanks, 2.0.0 released
