### ISSUE TITLE
Customer Ajax Login in Checkout is broken

### ISSUE THREAD

**Issue by norgeindian** [iMi-digital/magento2-friendly-captcha#37]
In https://github.com/iMi-digital/magento2-friendly-captcha/commit/1a70dd3266c6ef43cc64c663e6473ebfa1496e3b the observer `imi_friendly_captcha_ajax_login been` has been activated in `etc/frontend/events.xml`.
Unfortunately, the observer `IMI\FriendlyCaptcha\Observer\Frontend\AjaxLoginObserver` does not exist and is commented out in `etc/frontend/di.xml`.
I don't know if it is as easy as removing the comments in the AjaxLogin Form section of `etc/frontend/di.xml`, but in the current status, you can not log in anymore in the checkout.

**Comment by amenk** [comment]
FYI @DanieliMi

**Comment by amenk** [comment]
@norgeindian Thanks for reporting. In a shop with 2.0.0 of this plugin we seem to have such a problem.
`/rest/german/V1/customers/isEmailAvailable` seems to yield true, even if the account is existing.

Is this the same problem you are seeing? Or do you get an error message?

**Comment by norgeindian** [comment]
@amenk, we're using Onestepcheckout. Don't know if that makes a difference, but wanted to mention it.
My issue is actually a bit different.
So as soon as we try to log in in the checkout with version `2.0.1`of the module, we're getting the error message `Could not authenticate. Please try again later`. and in the `system.log`, I have the following error message:

> Class "IMI\FriendlyCaptcha\Observer\Frontend\AjaxLoginObserver" does not exist

Like I wrote. That error message seems to make sense to me, as the observer definitely does not exist.

Maybe your issue comes from https://github.com/magento/magento2/issues/37716 ?
Magento recently introduced a new setting, which disables the checkout login feature by default.
See https://github.com/magento/magento2/issues/37716#issuecomment-1621444796 for further information.

**Comment by amenk** [comment]
Yep, you are right, we disabled the guest checkout.

**Comment by iranimij** [comment]
In general, we need to enable a captcha for this form as well, since it's the main intent of this module, but for now, I think fixing this issue is more important, so I have pushed my codes and created a new PR. in the future, we can add a captcha to this form as well.

**Comment by DanieliMi** [comment]
Fixed in [2.0.2](https://github.com/iMi-digital/magento2-friendly-captcha/releases/tag/2.0.2).
