### ISSUE TITLE
Encrypt API Key

### ISSUE THREAD

**Issue by sprankhub** [iMi-digital/magento2-friendly-captcha#8]
Currently, the API key is stored completely unencrypted. IMHO, it should be stored encrypted. Therefore:

Change type and backend model similar to the one here in `system.xml`:

https://github.com/magento/magento2/blob/84e7dfaf95401d0f431094d55ccb88c36526a6eb/app/code/Magento/Directory/etc/adminhtml/system.xml#L39-L44

Change backend model similar to the one here in `config.xml`:

https://github.com/magento/magento2/blob/84e7dfaf95401d0f431094d55ccb88c36526a6eb/app/code/Magento/Directory/etc/config.xml#L23

Write patch, which converts all existing, unencrypted values to encrypted values to not break existing integrations.

**Comment by amenk** [comment]
Yes. Low prio at the moment, but a PR including the data patch would be welcome.
